"""added_session_and_query_table

Revision ID: 92ee6cfa4c06
Revises: f557805ceb4f
Create Date: 2024-03-18 10:32:40.231094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ee6cfa4c06'
down_revision = 'f557805ceb4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('StockCode', sa.String(length=256), nullable=False),
    sa.Column('Description', sa.String(length=512), nullable=False),
    sa.Column('UnitPrice', sa.Float(), nullable=False),
    sa.Column('InvoiceNo', sa.Integer(), nullable=False),
    sa.Column('InvoiceDate', sa.DateTime(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Country', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_id'), 'dataset', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('user_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('SessionID', sa.UUID(), nullable=True),
    sa.Column('QueryText', sa.String(), nullable=True),
    sa.Column('ResponseText', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['SessionID'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_queries_id'), 'user_queries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_queries_id'), table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_dataset_id'), table_name='dataset')
    op.drop_table('dataset')
    # ### end Alembic commands ###
